import day7.part1
import day7.traceTachyon
import day7.visualizeTracing
import org.assertj.core.api.Assertions.assertThat
import kotlin.test.Test

class Day7Tests {

    @Test
    fun testTracing() {
        val expected = """
            .......|.......
            .......|.......
            ......|^|......
            ......|.|......
            .....|^|^|.....
            .....|.|.|.....
            ....|^|^|^|....
            ....|.|.|.|....
            ...|^|^|||^|...
            ...|.|.|||.|...
            ..|^|^|||^|^|..
            ..|.|.|||.|.|..
            .|^|||^||.||^|.
            .|.|||.||.||.|.
            |^|^|^|^|^|||^|
            |.|.|.|.|.|||.|
        """.trimIndent()

        val preparedInput = testInput.lines().map { it.toCharArray() }

        val trace = traceTachyon(preparedInput)

        val actual = visualizeTracing(preparedInput, trace.points)
        println(actual)

        assertThat(actual).isEqualTo(expected)
    }

    @Test
    fun testPart1() {
        val preparedInput = testInput.lines().map { it.toCharArray() }

        val actual  = part1(preparedInput)

        assertThat(actual).isEqualTo(21)
    }

    companion object {
        val testInput = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
        """.trimIndent()
    }
}